### ISSUE TITLE
Suggestion: Use vm

### ISSUE THREAD

**Issue by legodude17** [eslachance/djs-selfbot#2]
First let me say, thank you for the great example and book.

Second, I think it would be an interesting idea to use `vm.runInThisContext()` instead of `eval()`, because it is much safer, you can also control the environment that it is run in.

**Comment by eslachance** [comment]
Oh wow I really should be paying more attention to my notifications on github, my apologies!

The whole point of using eval is to *actually* influence the discord environment. By running into a vm, if I decide to do a message.delete, or an edit message, or *whatever* (which is what I normally do with it!), then it cannot run in `vm`.

**Comment by legodude17** [comment]
You could included the bot in the context, then it could do stuff like that, but I see where you are coming from.
